### ISSUE TITLE
KeyError when running straingst cluster

### ISSUE THREAD

**Issue by samnooij** [broadinstitute/StrainGE#12] opened 2022-06-01 14:29 UTC
I have installed StrainGE version 1.3 through conda and am trying to follow the database creation tutorial from [readthedocs](https://strainge.readthedocs.io/en/latest/create-database.html#). Everything seems to work fine until the `straingst cluster` step. The stderr looks like:

```
2022-06-01 16:02:48,190 - INFO:root:Reading pairwise similarities...
Traceback (most recent call last):
  File "... miniconda3/envs/strainge/bin/straingst", line 11, in <module>
    sys.exit(straingst_cli())
  File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/main.py", line 110, in __call__
    self.run(args)
  File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/registry.py", line 83, in run
    rc = subcommand_func(**args_dict)
  File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 476, in __call__
    sim_matrix = cluster.similarities_to_matrix(similarities, labels, 'ani')
  File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cluster.py", line 47, in similarities_to_matrix
    i = label_ix[str(kmerset1)]
KeyError: 'Esch_coli_106_GCF_005222345.1'
```
Where the 'key' is the first _E. coli_ genome in the `similarities.tsv` file (`kmerset1`).

The command I tried to run is:

```bash
straingst cluster -i data/tmp/strainge_similarities.tsv -d -C 0.99 -c 0.90\
 --clusters-out data/tmp/strainge_clusters.tsv\
 strainge_db/*.hdf5 > data/tmp/references_to_keep.txt
```

(Basically exactly like the example on readthedocs, right?)

I already tried re-running `kmerize`, `kmersim` and `cluster`, but that didn't help. I'll do my best to provide more information if that is needed to find the problem.
Could this be an issue with the Python version? I have Python v3.9.12 in that environment. Any idea what might be going wrong? Thanks in advance!

_P.S. If it helps: I found the Python error refers to_ 
https://github.com/broadinstitute/StrainGE/blob/d9c77b01d3f3b88d2396d8c07ba09a4c4960cf4c/src/strainge/cluster.py#L47

**Comment by lrvdijk** [comment] 2022-06-01 21:40
Can you share me your similarities file? Might have some left-over file extensions in that file, which prevents it from looking up the correct entry? Or share the command you used to generate the HDF5 kmersets.

**Comment by samnooij** [comment] 2022-06-02 09:16
Thank you for the quick response! Here is a download link to the similarities file (180MB): https://send.tresorit.com/a#fbZww_olVhsv2YzU6U-rRA (available for one week).

This is the command I used to kmerize:

```bash
parallel --rpl '{%(.+?)} s/$$1$//;' -j 12 straingst kmerize -o {%.fa.gz}.hdf5 {}\
 ::: data/strainge_db/*.fa.gz
```
(The replace code removes the file extension '.fa.gz' - I got that from [this tutorial](https://www.gnu.org/software/parallel/parallel_tutorial.html#replacement-strings))

**Comment by JX-Zhong** [comment] 2022-09-21 02:31
Hi, I had the same question and error. Have you solved it?

**Comment by lrvdijk** [comment] 2022-09-23 14:18
Sorry I have been sidetracked with other projects, I'll give it a look next week!

**Comment by kebow** [comment] 2023-04-06 03:27
Just wondering if there is any update on this issue? I'm also having the problem, but only with some sets of genomes. The similarities.tsv file appears to be made without error but the cluster step fails as below:
```
2023-04-06 13:14:10,340 - INFO:root:Clustering genomes...
2023-04-06 13:14:10,373 - INFO:root:Picking a representive genome per cluster...
Traceback (most recent call last):
  File "/srv/home/user/.conda/envs/strainge_1.3.7/bin/straingst", line 11, in <module>
    sys.exit(straingst_cli())
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/main.py", line 110, in __call__
    self.run(args)
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/registry.py", line 83, in run
    rc = subcommand_func(**args_dict)
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 517, in __call__
    similarities = similarities.loc[(to_keep, to_keep), :].copy()
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1247, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 941, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1047, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1305, in _getitem_axis
    locs = labels.get_locs(key)
  File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 3432, in get_locs
    raise KeyError(seq)
KeyError: (['SE3129_concoct_bins.tsv.004_porechop'], ['SE3129_concoct_bins.tsv.004_porechop'])
```
Hoping there's a fix! My commands were:

```
for f in *.fna; do straingst kmerize -o ${f%.fna}.hdf5 $f; done

straingst kmersim --all-vs-all -t 16 -S jaccard -S subset *.hdf5 > similarities.tsv

straingst cluster -i similarities.tsv -d -C 0.99 -c 0.90 --clusters-out clusters.tsv *.hdf5 > references_to_keep.txt
```
My similarities files is attached: [similarities.zip](https://github.com/broadinstitute/StrainGE/files/11166127/similarities.zip)

**Comment by YanmeiZhao** [comment] 2023-04-19 07:02
> Just wondering if there is any update on this issue? I'm also having a similar issue, but only with some sets of genomes. The similarities.tsv file appears to be made without error but the cluster step fails as below:
> 
> ```
> 2023-04-06 13:14:10,340 - INFO:root:Clustering genomes...
> 2023-04-06 13:14:10,373 - INFO:root:Picking a representive genome per cluster...
> Traceback (most recent call last):
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/bin/straingst", line 11, in <module>
>     sys.exit(straingst_cli())
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/main.py", line 110, in __call__
>     self.run(args)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/registry.py", line 83, in run
>     rc = subcommand_func(**args_dict)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 517, in __call__
>     similarities = similarities.loc[(to_keep, to_keep), :].copy()
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
>     return self._getitem_tuple(key)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1247, in _getitem_tuple
>     return self._getitem_lowerdim(tup)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 941, in _getitem_lowerdim
>     return self._getitem_nested_tuple(tup)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1047, in _getitem_nested_tuple
>     obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1305, in _getitem_axis
>     locs = labels.get_locs(key)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 3432, in get_locs
>     raise KeyError(seq)
> KeyError: (['SE3129_concoct_bins.tsv.004_porechop'], ['SE3129_concoct_bins.tsv.004_porechop'])
> ```
> 
> Hoping there's a fix! My commands were:
> 
> ```
> for f in *.fna; do straingst kmerize -o ${f%.fna}.hdf5 $f; done
> 
> straingst kmersim --all-vs-all -t 16 -S jaccard -S subset *.hdf5 > similarities.tsv
> 
> straingst cluster -i similarities.tsv -d -C 0.99 -c 0.90 --clusters-out clusters.tsv *.hdf5 > references_to_keep.txt
> ```
> 
> My similarities files is attached: [similarities.zip](https://github.com/broadinstitute/StrainGE/files/11166127/similarities.zip)

**Comment by YanmeiZhao** [comment] 2023-04-19 07:06
> Just wondering if there is any update on this issue? I'm also having a similar issue, but only with some sets of genomes. The similarities.tsv file appears to be made without error but the cluster step fails as below:
> 
> ```
> 2023-04-06 13:14:10,340 - INFO:root:Clustering genomes...
> 2023-04-06 13:14:10,373 - INFO:root:Picking a representive genome per cluster...
> Traceback (most recent call last):
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/bin/straingst", line 11, in <module>
>     sys.exit(straingst_cli())
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/main.py", line 110, in __call__
>     self.run(args)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/registry.py", line 83, in run
>     rc = subcommand_func(**args_dict)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 517, in __call__
>     similarities = similarities.loc[(to_keep, to_keep), :].copy()
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
>     return self._getitem_tuple(key)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1247, in _getitem_tuple
>     return self._getitem_lowerdim(tup)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 941, in _getitem_lowerdim
>     return self._getitem_nested_tuple(tup)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1047, in _getitem_nested_tuple
>     obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexing.py", line 1305, in _getitem_axis
>     locs = labels.get_locs(key)
>   File "/srv/home/user/.conda/envs/strainge_1.3.7/lib/python3.9/site-packages/pandas/core/indexes/multi.py", line 3432, in get_locs
>     raise KeyError(seq)
> KeyError: (['SE3129_concoct_bins.tsv.004_porechop'], ['SE3129_concoct_bins.tsv.004_porechop'])
> ```
> 
> Hoping there's a fix! My commands were:
> 
> ```
> for f in *.fna; do straingst kmerize -o ${f%.fna}.hdf5 $f; done
> 
> straingst kmersim --all-vs-all -t 16 -S jaccard -S subset *.hdf5 > similarities.tsv
> 
> straingst cluster -i similarities.tsv -d -C 0.99 -c 0.90 --clusters-out clusters.tsv *.hdf5 > references_to_keep.txt
> ```
> 
> My similarities files is attached: [similarities.zip](https://github.com/broadinstitute/StrainGE/files/11166127/similarities.zip)

I met the same issue. Have you found solution for it ? I wanted prepared db with Pseu_putide genomes from NCBI, but faild when using "straingst cluster" command.

**Comment by kebow** [comment] 2023-04-19 23:33
No sorry I haven't looked into it any further to try to figure out what is shared by the datasets that fail vs those that don't. Just working with the ones that work for now!

**Comment by YanmeiZhao** [comment] 2023-04-20 02:31
Thanks for your reply. But no ones work in my dataset from NCBI and I can not find the solution up to now.

                       
原始邮件
                       
                     

发件人："kebow"< ***@***.*** &gt;;

发件时间：2023/4/20 7:34

收件人："broadinstitute/StrainGE"< ***@***.*** &gt;;

抄送人："YanmeiZhao"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [broadinstitute/StrainGE] KeyError when running straingst cluster(Issue #12)




 
No sorry I haven't looked into it any further to try to figure out what is shared by the datasets that fail vs those that don't. Just working with the ones that work for now!

**Comment by ValentinCledassou** [comment] 2023-05-24 10:17
Same problem here with strainge cluster. I havve used the basic code of the tutorial before this step. But the genus extracted from refseq in my case is Clostridium

**Comment by camilagazolla** [comment] 2023-06-19 06:43
I am getting the same error. Has anyone found out how to overcome this problem?

**Comment by camilagazolla** [comment] 2023-06-28 06:27
> I have installed StrainGE version 1.3 through conda and am trying to follow the database creation tutorial from [readthedocs](https://strainge.readthedocs.io/en/latest/create-database.html#). Everything seems to work fine until the `straingst cluster` step. The stderr looks like:
> 
> ```
> 2022-06-01 16:02:48,190 - INFO:root:Reading pairwise similarities...
> Traceback (most recent call last):
>   File "... miniconda3/envs/strainge/bin/straingst", line 11, in <module>
>     sys.exit(straingst_cli())
>   File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/main.py", line 110, in __call__
>     self.run(args)
>   File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/registry.py", line 83, in run
>     rc = subcommand_func(**args_dict)
>   File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cli/kmersets.py", line 476, in __call__
>     sim_matrix = cluster.similarities_to_matrix(similarities, labels, 'ani')
>   File "... miniconda3/envs/strainge/lib/python3.9/site-packages/strainge/cluster.py", line 47, in similarities_to_matrix
>     i = label_ix[str(kmerset1)]
> KeyError: 'Esch_coli_106_GCF_005222345.1'
> ```
> 
> Where the 'key' is the first _E. coli_ genome in the `similarities.tsv` file (`kmerset1`).
> 
> The command I tried to run is:
> 
> ```shell
> straingst cluster -i data/tmp/strainge_similarities.tsv -d -C 0.99 -c 0.90\
>  --clusters-out data/tmp/strainge_clusters.tsv\
>  strainge_db/*.hdf5 > data/tmp/references_to_keep.txt
> ```
> 
> (Basically exactly like the example on readthedocs, right?)
> 
> I already tried re-running `kmerize`, `kmersim` and `cluster`, but that didn't help. I'll do my best to provide more information if that is needed to find the problem. Could this be an issue with the Python version? I have Python v3.9.12 in that environment. Any idea what might be going wrong? Thanks in advance!
> 
> _P.S. If it helps: I found the Python error refers to_
> 
> https://github.com/broadinstitute/StrainGE/blob/d9c77b01d3f3b88d2396d8c07ba09a4c4960cf4c/src/strainge/cluster.py#L47

did you find an answer to this  problem @samnooij ?

**Comment by biolene** [comment] 2023-07-20 09:18
I think I have identified the cause of this problem (at least for the ones encountering this issue after April this year). I had the same error, with StrainGE 1.3.7 pip installed in a Python 3.8.10 virtual environment. I could solve it by downgrading pandas to 1.5.3 (or lower). With pandas 2.0.0 and above (released in April 2023) it failed. 
When running the straingst cluster command with pandas 1.5.3 it succeeds but produces the following warning:
`/strainge/cli/kmersets.py:517: FutureWarning: The behavior of indexing on a MultiIndex with a nested sequence of labels is deprecated and will change in a future version. `series.loc[label, sequence]` will raise if any members of 'sequence' or not present in the index's second level. To retain the old behavior, use `series.index.isin(sequence, level=1)`
  similarities = similarities.loc[(to_keep, to_keep), :].copy()`

I reckon this change in the behavior of pandas as of version 2.0.0 causes the issue and should be quite easy to fix (which I kindly leave up to the developer to implement :)

**Comment by joelewis101** [comment] 2023-10-24 09:18
Same problem for me - downgrading SciPy to 1.10 (as per #34 ) and pandas to 1.5.3 worked, @biolene  you are a hero .

**Closed** 2023-10-27 16:57 UTC

**Comment by lrvdijk** [comment] 2023-10-27 17:57
This should be fixed in the upcoming release, available on PyPI soon!
